robot_arm:
  ros__parameters:
    # publish all joints states
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # position controllers and set up PID
    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: Revolute_3
      pid: {p: 700, i: 50, d: 70}

    joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: Revolute_4
      pid: {p: 700, i: 50, d: 70}


# controller_manager:
#   ros__parameters:
#     update_rate: 100 # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     joint1_position_controller:
#       type: position_controllers/JointGroupPositionController
#       joints:
#         - Revolute_3

#     joint2_position_controller:
#       type: position_controllers/JointGroupPositionController
#       joints:
#         - Revolute_4

# joint1_position_controller:
#   ros__parameters:
#     joints:
#       - Revolute_3

# joint2_position_controller:
#   ros__parameters:
#     joints:
#       - Revolute_4
      
