controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint1_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - Revolute_3
      gains:
        Revolute_3:
          p: 700.0
          i: 50.0
          d: 70.0

    joint2_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - Revolute_4
      gains:
        Revolute_4:
          p: 700.0
          i: 50.0
          d: 70.0